#include "filemanager.h"

FileManager* FileManager::fm = nullptr;


FileManager::FileManager()
{
    if(fm == nullptr)
        fm = this;
    else delete this;
    od = new OpeningDialog();
}

FileManager::~FileManager()
{
    delete od;
}


bool FileManager::OpenFile(QString filePath, QString fileName)
{
    if(ShouldOpenFile(filePath, fileName))
    {
        if(currentFile.isOpen())
            CloseCurrentFile();

        currentFile.setFileName(filePath); //this function being called setfilename makes no sense
        if(currentFile.open(QFile::ReadWrite))
        {
            if(shouldOverwriteCurrentFile())
                OverwriteCurrentFile();

            OnOpenFile();
            return true;
        }
        else return false;
    }
    else
    {
        qDebug() << "File Should not be opened";
        return false;
    }
}


bool FileManager::shouldOverwriteCurrentFile()
{
    return overwrite;
}

void FileManager::CloseCurrentFile()
{
    OnFileClose();
    currentFile.flush();
    currentFile.close();
}

void FileManager::OnFileClose()
{
    //make sure the file saves before closing here
}


void FileManager::OverwriteCurrentFile()
{
    qDebug() << "File overwritten";
    //overwrite here
    overwrite = false; //reset overwrite flag
}

void FileManager::OnOpenFile()
{
    qDebug() << "File Opened";
    //open corrent graphspaces, load block positions and connections here
}



bool FileManager::ShouldOpenFile(QString filePath, QString fileName)
{
    QFile tmpFile;
    tmpFile.setFileName(filePath);//this function being called setFileName makes no sense

    if(!tmpFile.open(QFile::ReadWrite))
    {
        qDebug() << "Did not open";
        return false;
    }
    else
    {
        QTextStream in(&tmpFile);

        QString firstLine = in.readLine(0);

        if(firstLine.contains(("--Generated by Deflow--")))
        {

            tmpFile.flush();
            tmpFile.close();
            return true;
        }
        else
        {
            od->SetFile(fileName);
            od->exec();

            tmpFile.flush();
            tmpFile.close();
            overwrite = od->result();
            return od->result();
        }
    }
}

